# Generated by Django 3.2.7 on 2021-09-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=140)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zip', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=155)),
                ('date', models.DateField()),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('image', models.URLField()),
                ('advertsing', models.URLField()),
                ('status', models.BooleanField(default=False)),
                ('commission', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='events.eventtypemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
