# Generated by Django 3.2.7 on 2021-09-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=155)),
                ('spotfy', models.URLField()),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('img', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_id', to='events.eventmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
