# Generated by Django 3.2.7 on 2021-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=155)),
                ('account', models.IntegerField()),
                ('agency', models.IntegerField()),
                ('digit', models.IntegerField()),
            ],
        ),
    ]
