# Generated by Django 3.2.7 on 2021-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0002_consumablesale_salec'),
    ]

    operations = [
        migrations.AddField(
            model_name='salec',
            name='consumable_type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
